name: Berlin Appointment Checker

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

concurrency:
  group: berlin_appointment_checker
  cancel-in-progress: true  

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.7"

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/0.4.20/install.sh | sh

    - name: Install project dependencies
      run: |
        uv sync

    - name: Install Chromium in Playwright
      run: |
        uv run playwright install --with-deps chromium

    - name: Run Berlin Appointment Checker
      env:
        APPOINTMENT_ID: ${{ vars.APPOINTMENT_ID }}
        TWILIO_ACCOUNT_SID: ${{ vars.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_FROM_NO_WHATSAPP: ${{ vars.TWILIO_FROM_NO_WHATSAPP }}
        TWILIO_TO_NO: ${{ vars.TWILIO_TO_NO }}
      run: |
        uv run -m app
